### ISSUE TITLE
python2.7 can't execute run_ida_script.py

### ISSUE THREAD

**Issue by jinyu00** [williballenthin/python-idb#41] opened 2018-07-26 23:44 UTC
```
~/python-idb-0.4.0/scripts$ python run_ida_script.py 
Traceback (most recent call last):
  File "run_ida_script.py", line 11, in <module>
    import importlib.abc
ImportError: No module named abc

```

**Comment by williballenthin** [comment] 2018-07-30 16:19
`run_ida_script.py` only supports Python 3+ due to differences in the import system. I'll accept contributions that add support py2 support; however, I don't expect to have the capacity to implement and maintain the system myself right now.

I will update the script to throw an error that actually describes what the issue is.

**Comment by williballenthin** [comment] 2018-07-30 16:41
addressed in d46d1c94d60f15c942bd4c4593b396df55241bf6

thanks for reporting the issue @jinyu00 !

**Comment by williballenthin** [comment] 2018-07-30 16:42
```
$ ~/env2/bin/python ./scripts/run_ida_script.py ./scripts/yara_fn.py test.idb
Traceback (most recent call last):
  File "./scripts/run_ida_script.py", line 15, in <module>
    import idb.shim
  File "/mnt/c/Users/user/Documents/code/python-idb/idb/shim.py", line 3, in <module>
    raise NotImplementedError('Python 3+ only for shimming the import system to work like IDA Pro.')
NotImplementedError: Python 3+ only for shimming the import system to work like IDA Pro.
```

**Comment by williballenthin** [comment] 2018-07-30 17:03
added support for py2 shimming in ccb453c6c9f2459c697f5612479dee80c2ed6249

**Closed by williballenthin** 2018-07-30 17:03 UTC
