### ISSUE TITLE
GetManyBytes fails on reaching dup/reserved bytes

### ISSUE THREAD

**Issue by freetink3r** [williballenthin/python-idb#29] opened 2017-12-21 02:12 UTC
The GetManyBytes function is throwing an exception upon reaching an address that maps to a duplicated/reserved section of bytes, which are often used for alignment padding.  See the attached screenshot for a troublesome location at address 0x180072125 in kernel32 from Windows 10.  The idc.GetManyBytes in IDA correctly returns the bytes.

![screen shot 2017-12-20 at 9 12 01 pm](https://user-images.githubusercontent.com/5585976/34237394-77a3f834-e5ca-11e7-9bcd-5dba0a2454b3.png)

**Comment by williballenthin** [comment] 2017-12-24 02:33
would you share the hash (or idb) for this particular file? i'm having trouble reproducing on my test data.

**Comment by freetink3r** [comment] 2017-12-24 19:45
Sure thing, I just wrote a test.  Would you add me as a collaborator to the repo?

**Comment by williballenthin** [comment] 2017-12-25 02:45
I'd recommend forking this project and then submitting a pull request. I find it easier to track parallel work this way.

**Comment by williballenthin** [comment] 2017-12-29 16:34
Here's what I've found inspecting the .i64 file:

The ID1 section contains the raw bytes and flags for defined addresses in the database. This is somewhat like a section in a PE file on disk. The Segments enumerated via `idc.FirstSeg/NextSeg` come from the results of analysis that are stored in the btree. This is kind of like whats in memory once a PE has been loaded. Likewise, rawsize is not always equal to virtualsize.

Right now, `idc.GetManyBytes` simply tries to fetch the byte value from the ID1 section, and fails if the address does not fall within a "raw section". IDA Pro seems to handle reads across the entire "virtual section", including the padding/alignment region at the end of a segment.

I'll update `idc.GetManyBytes` to return the value `00` for bytes beyond the raw section yet within the virtual section bounds.

**Comment by williballenthin** [comment] 2017-12-29 16:38
In reviewing the code for `idc.GetManyBytes` there are some serious optimizations that we can make to the code if its unreasonably slow. I won't do this until requested, however, since it may complicate the code a bit, and I highly value the code being readable whenever reasonable.

**Comment by williballenthin** [comment] 2017-12-29 17:01
this issue is addressed in 61d141152b66864cd4f29e942cdf4f8a168f2179.

thanks to @freetink3r for reporting the issue and providing a test case!

**Closed by williballenthin** 2017-12-29 17:01 UTC
Labels: bug

**Comment by williballenthin** [comment] 2017-12-29 17:04
I made the fix to `idc.GetManyBytes`, but upon further reflection, perhaps a better place to make it might have been `idc.IdbByte`, since I bet that API also has the same issue. Fortunately, I think that API is much less used, so we'll stick to our current solution until someone complains 👼.

Ultimately, the byte fetching routines should be refactored for better performance, so we'll punt until then.
